---
- name: Delete New Users
  hosts: all
  tasks:
    - name: Delete User Task
      user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop:
        - postgres
        - barman
...
